In [1]:
import numpy as np

In [24]:
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [27]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [31]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [36]:
a = np.arange(0,10,3)
print(a)

[0 3 6 9]


In [39]:
a = np.arange(100)
b = a ** 2
print(b)

[   0    1    4    9   16   25   36   49   64   81  100  121  144  169
  196  225  256  289  324  361  400  441  484  529  576  625  676  729
  784  841  900  961 1024 1089 1156 1225 1296 1369 1444 1521 1600 1681
 1764 1849 1936 2025 2116 2209 2304 2401 2500 2601 2704 2809 2916 3025
 3136 3249 3364 3481 3600 3721 3844 3969 4096 4225 4356 4489 4624 4761
 4900 5041 5184 5329 5476 5625 5776 5929 6084 6241 6400 6561 6724 6889
 7056 7225 7396 7569 7744 7921 8100 8281 8464 8649 8836 9025 9216 9409
 9604 9801]


In [47]:
# 1. Buat array dari 1 sampai 10
a = np.arange(1,11)
print(a)

# 2. Hitung rata-rata dan standar deviasi dari array tsb
print(np.std(a))

# 3. Ambil elemen genap dari array tsb
print(a[a % 2 == 0])

[ 1  2  3  4  5  6  7  8  9 10]
2.8722813232690143
[ 2  4  6  8 10]


In [53]:
m = np.array([[1,2,3],
              [4,5,6]])
print(m.shape)
print(m[0,0])
print(m[1,2])
print(m[0])
print(m[:, 1])

(2, 3)
1
6
[1 2 3]
[2 5]


In [62]:
a = np.array([[1,2],
              [3,4]])

b = np.array([[5,6],
              [7,8]])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [68]:
print(a)
print(b)
print(np.dot(a,b))
# print(a.T)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]


In [72]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])   # akan ditambahkan ke tiap baris
print(a + b)


[[11 22 33]
 [14 25 36]]


In [78]:
# 1. Buat matriks 3x3 dari angka 1 sampai 9
a = np.arange(1,10).reshape(3,3)
print(a)
# 2. Kalikan setiap elemen dengan 2
a = a * 2
print(a)
# 3. Ambil baris ke-2 dan kolom ke-3
print(a[1,2])
# 4. Hitung determinan dari matriks itu

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
12
